# K-means clustering

# Importing Libaries

In [1]:
import cv2
import numpy as np

In [5]:
img=cv2.imread("C:/Users/admin/Downloads/ney.jpg")

In [6]:
img

array([[[20,  6,  8],
        [20,  6,  8],
        [22,  5,  8],
        ...,
        [26,  8,  7],
        [25,  7,  6],
        [24,  6,  5]],

       [[22,  8, 10],
        [22,  8, 10],
        [24,  7, 10],
        ...,
        [24,  6,  5],
        [25,  7,  6],
        [25,  7,  6]],

       [[24, 10, 11],
        [24, 10, 11],
        [26, 10, 11],
        ...,
        [22,  4,  3],
        [24,  6,  5],
        [26,  8,  7]],

       ...,

       [[25,  7,  6],
        [25,  7,  6],
        [25,  7,  6],
        ...,
        [25,  7,  6],
        [25,  7,  6],
        [24,  6,  5]],

       [[25,  7,  6],
        [25,  7,  6],
        [25,  7,  6],
        ...,
        [25,  7,  6],
        [25,  7,  6],
        [24,  6,  5]],

       [[25,  7,  6],
        [25,  7,  6],
        [25,  7,  6],
        ...,
        [25,  7,  6],
        [25,  7,  6],
        [24,  6,  5]]], dtype=uint8)

# RGB CONVERTION

In [9]:
imgrgb=cv2.cvtColor(img,cv2.COLOR_BGR2RGB)

In [11]:
vec = imgrgb.reshape((-2,4))
vec

array([[ 8,  6, 20,  8],
       [ 6, 20,  8,  5],
       [22,  8,  5, 22],
       ...,
       [ 6,  7, 25,  6],
       [ 7, 25,  6,  7],
       [25,  5,  6, 24]], dtype=uint8)

In [12]:
vec = np.float32(vec)
vec

array([[ 8.,  6., 20.,  8.],
       [ 6., 20.,  8.,  5.],
       [22.,  8.,  5., 22.],
       ...,
       [ 6.,  7., 25.,  6.],
       [ 7., 25.,  6.,  7.],
       [25.,  5.,  6., 24.]], dtype=float32)

# iteration termination criteria

In [13]:
criteria = (cv2.TERM_CRITERIA_EPS+cv2.TERM_CRITERIA_MAX_ITER,100,1)

# cluster condition

In [14]:
k = 3
attempts = 100

In [15]:
compactness,label,center = cv2.kmeans(vec,k,None,criteria,attempts,cv2.KMEANS_PP_CENTERS)
center

array([[ 77.83708 ,  70.01858 ,  68.30726 ,  77.21762 ],
       [163.66096 , 162.39459 , 162.8103  , 164.0475  ],
       [ 19.057852,  21.316364,  21.9126  ,  19.015947]], dtype=float32)

In [17]:
center =np.uint8(center)
center

array([[ 77,  70,  68,  77],
       [163, 162, 162, 164],
       [ 19,  21,  21,  19]], dtype=uint8)

In [20]:
res = center[label.flatten()]
res_img=res.reshape((imgrgb.shape))
res_img

array([[[19, 21, 21],
        [19, 19, 21],
        [21, 19, 19],
        ...,
        [21, 21, 19],
        [19, 21, 21],
        [19, 19, 21]],

       [[21, 19, 19],
        [21, 21, 19],
        [19, 21, 21],
        ...,
        [19, 19, 21],
        [21, 19, 19],
        [21, 21, 19]],

       [[19, 21, 21],
        [19, 19, 21],
        [21, 19, 19],
        ...,
        [21, 21, 19],
        [19, 21, 21],
        [19, 19, 21]],

       ...,

       [[21, 19, 19],
        [21, 21, 19],
        [19, 21, 21],
        ...,
        [19, 19, 21],
        [21, 19, 19],
        [21, 21, 19]],

       [[19, 21, 21],
        [19, 19, 21],
        [21, 19, 19],
        ...,
        [21, 21, 19],
        [19, 21, 21],
        [19, 19, 21]],

       [[21, 19, 19],
        [21, 21, 19],
        [19, 21, 21],
        ...,
        [19, 19, 21],
        [21, 19, 19],
        [21, 21, 19]]], dtype=uint8)

In [22]:
cv2.imshow("img",img)
cv2.imshow("segmented",res_img)
cv2.waitKey(0)
cv2.destroyAllWindows()

In [26]:
img=cv2.imread("C:/Users/admin/Downloads/ney.jpg")
segmented_image=cv2.pyrMeanShiftFiltering(img,40,40)
cv2.imshow("img",img)
cv2.imshow("segmented_image",segmented_image)
cv2.waitKey(0)
cv2.destroyAllWindows()